# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Digital Fabrication
tagline:          'Lucas Leite'
description:      'My personal blog.'
url:              http://lucasrolim7.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Lucas Leite
  url:            https://www.facebook.com/lucasrolim7

paginate:         5

# Custom vars
icon:             /assets/images/icon.png
cover:            lucasrolim7.github.io/assets/images/cover_2.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/lucasrolim7
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/lucasrolim7
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          https://google.com/+IanCamporezBrunelli
    desc:         Add me on google+

  - icon:         feed
    url:          https://www.facebook.com/lucasrolim7
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Lucas Leite
  url:            http://lucasrolim7.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
